version: '2'
services:
    gorest:
        build: .
        restart: unless-stopped
        ports:
            - "8080:8080"
        links:
            - mongo
        depends_on: 
            - mongo
        volumes:
            - ./logs:/var/log/gorest:rw         
            - ./config.json.prod:/config.json
    mongo:
        image: mvertes/alpine-mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
